//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
 * Copyright 2019 The original author or authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by openapi-gen. DO NOT EDIT.

package openapi

import (
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return nil
}

func schema_pkg_apis_build_v1alpha1_Build(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha1_BuildList(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha1_BuildSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha1_BuildStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha1_Builder(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha1_BuilderList(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha1_BuilderSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha1_BuilderStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha1_ClusterBuilder(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha1_ClusterBuilderList(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha1_ClusterBuilderSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha1_ClusterStack(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha1_ClusterStackList(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha1_ClusterStackSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha1_ClusterStackSpecImage(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha1_ClusterStackStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha1_ClusterStackStatusImage(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha1_ClusterStore(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha1_ClusterStoreList(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha1_ClusterStoreSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha1_ClusterStoreStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha1_Image(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha1_ImageBuild(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha1_ImageList(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha1_ImageSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha1_ImageStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha1_LastBuild(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha1_NamespacedBuilderSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha1_ResolvedClusterStack(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha1_SourceResolver(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha1_SourceResolverList(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha1_SourceResolverSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha1_SourceResolverStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha2_Build(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha2_BuildCache(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha2_BuildCacheConfig(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha2_BuildList(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha2_BuildPersistentVolumeCache(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha2_BuildSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha2_BuildSpecImage(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha2_BuildStack(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha2_BuildStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha2_Builder(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha2_BuilderBuildpackRef(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha2_BuilderList(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha2_BuilderOrderEntry(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha2_BuilderSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha2_BuilderStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha2_Buildpack(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha2_BuildpackList(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha2_BuildpackSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha2_BuildpackStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha2_ClusterBuilder(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha2_ClusterBuilderList(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha2_ClusterBuilderSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha2_ClusterBuildpack(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha2_ClusterBuildpackList(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha2_ClusterBuildpackSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha2_ClusterBuildpackStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha2_ClusterLifecycle(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha2_ClusterLifecycleList(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha2_ClusterLifecycleSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha2_ClusterLifecycleStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha2_ClusterLifecycleStatusImage(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha2_ClusterStack(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha2_ClusterStackList(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha2_ClusterStackSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha2_ClusterStackSpecImage(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha2_ClusterStackStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha2_ClusterStackStatusImage(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha2_ClusterStore(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha2_ClusterStoreList(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha2_ClusterStoreSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha2_ClusterStoreStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha2_CosignAnnotation(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha2_CosignConfig(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha2_CosignSignature(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha2_Image(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha2_ImageBuild(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha2_ImageBuilder(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha2_ImageCacheConfig(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha2_ImageList(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha2_ImagePersistentVolumeCache(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha2_ImageSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha2_ImageStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha2_LastBuild(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha2_NamespacedBuilderSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha2_RegistryCache(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha2_ResolvedClusterLifecycle(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha2_ResolvedClusterStack(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha2_SourceResolver(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha2_SourceResolverList(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha2_SourceResolverSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_build_v1alpha2_SourceResolverStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_core_v1alpha1_Blob(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_core_v1alpha1_BuildBuilderSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_core_v1alpha1_BuildStack(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_core_v1alpha1_BuildpackInfo(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_core_v1alpha1_BuildpackMetadata(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_core_v1alpha1_BuildpackRef(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_core_v1alpha1_BuildpackStack(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_core_v1alpha1_BuildpackStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_core_v1alpha1_BuildpackageInfo(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_core_v1alpha1_CNBBinding(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_core_v1alpha1_Condition(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_core_v1alpha1_Git(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_core_v1alpha1_ImageSource(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_core_v1alpha1_NotaryConfig(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_core_v1alpha1_NotarySecretRef(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_core_v1alpha1_NotaryV1Config(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_core_v1alpha1_OrderEntry(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_core_v1alpha1_Registry(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_core_v1alpha1_ResolvedBlobSource(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_core_v1alpha1_ResolvedGitSource(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_core_v1alpha1_ResolvedRegistrySource(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_core_v1alpha1_ResolvedSourceConfig(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_core_v1alpha1_SourceConfig(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_core_v1alpha1_Status(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_core_v1alpha1_VolatileTime(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}
