// Code generated by counterfeiter. DO NOT EDIT.
package clusterlifecyclefakes

import (
	"sync"

	"github.com/google/go-containerregistry/pkg/authn"
	"github.com/pivotal/kpack/pkg/apis/build/v1alpha2"
	"github.com/pivotal/kpack/pkg/reconciler/clusterlifecycle"
)

type FakeClusterLifecycleReader struct {
	ReadStub        func(authn.Keychain, v1alpha2.ClusterLifecycleSpec) (v1alpha2.ResolvedClusterLifecycle, error)
	readMutex       sync.RWMutex
	readArgsForCall []struct {
		arg1 authn.Keychain
		arg2 v1alpha2.ClusterLifecycleSpec
	}
	readReturns struct {
		result1 v1alpha2.ResolvedClusterLifecycle
		result2 error
	}
	readReturnsOnCall map[int]struct {
		result1 v1alpha2.ResolvedClusterLifecycle
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeClusterLifecycleReader) Read(arg1 authn.Keychain, arg2 v1alpha2.ClusterLifecycleSpec) (v1alpha2.ResolvedClusterLifecycle, error) {
	_ = "STUB: not implemented"
	return *new(v1alpha2.ResolvedClusterLifecycle), nil
}

func (fake *FakeClusterLifecycleReader) ReadCallCount() int { _ = "STUB: not implemented"; return 0 }

func (fake *FakeClusterLifecycleReader) ReadCalls(stub func(authn.Keychain, v1alpha2.ClusterLifecycleSpec) (v1alpha2.ResolvedClusterLifecycle, error)) {
	_ = "STUB: not implemented"
	return
}

func (fake *FakeClusterLifecycleReader) ReadArgsForCall(i int) (authn.Keychain, v1alpha2.ClusterLifecycleSpec) {
	_ = "STUB: not implemented"
	return *new(authn.Keychain), *new(v1alpha2.ClusterLifecycleSpec)
}

func (fake *FakeClusterLifecycleReader) ReadReturns(result1 v1alpha2.ResolvedClusterLifecycle, result2 error) {
	_ = "STUB: not implemented"
	return
}

func (fake *FakeClusterLifecycleReader) ReadReturnsOnCall(i int, result1 v1alpha2.ResolvedClusterLifecycle, result2 error) {
	_ = "STUB: not implemented"
	return
}

func (fake *FakeClusterLifecycleReader) Invocations() map[string][][]interface{} {
	_ = "STUB: not implemented"
	return nil
}

func (fake *FakeClusterLifecycleReader) recordInvocation(key string, args []interface{}) {
	_ = "STUB: not implemented"
	return
}

var _ clusterlifecycle.ClusterLifecycleReader = new(FakeClusterLifecycleReader)
