// Code generated by counterfeiter. DO NOT EDIT.
package clusterstackfakes

import (
	"sync"

	"github.com/google/go-containerregistry/pkg/authn"
	"github.com/pivotal/kpack/pkg/apis/build/v1alpha2"
	"github.com/pivotal/kpack/pkg/reconciler/clusterstack"
)

type FakeClusterStackReader struct {
	ReadStub        func(authn.Keychain, v1alpha2.ClusterStackSpec) (v1alpha2.ResolvedClusterStack, error)
	readMutex       sync.RWMutex
	readArgsForCall []struct {
		arg1 authn.Keychain
		arg2 v1alpha2.ClusterStackSpec
	}
	readReturns struct {
		result1 v1alpha2.ResolvedClusterStack
		result2 error
	}
	readReturnsOnCall map[int]struct {
		result1 v1alpha2.ResolvedClusterStack
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeClusterStackReader) Read(arg1 authn.Keychain, arg2 v1alpha2.ClusterStackSpec) (v1alpha2.ResolvedClusterStack, error) {
	_ = "STUB: not implemented"
	return *new(v1alpha2.ResolvedClusterStack), nil
}

func (fake *FakeClusterStackReader) ReadCallCount() int { _ = "STUB: not implemented"; return 0 }

func (fake *FakeClusterStackReader) ReadCalls(stub func(authn.Keychain, v1alpha2.ClusterStackSpec) (v1alpha2.ResolvedClusterStack, error)) {
	_ = "STUB: not implemented"
	return
}

func (fake *FakeClusterStackReader) ReadArgsForCall(i int) (authn.Keychain, v1alpha2.ClusterStackSpec) {
	_ = "STUB: not implemented"
	return *new(authn.Keychain), *new(v1alpha2.ClusterStackSpec)
}

func (fake *FakeClusterStackReader) ReadReturns(result1 v1alpha2.ResolvedClusterStack, result2 error) {
	_ = "STUB: not implemented"
	return
}

func (fake *FakeClusterStackReader) ReadReturnsOnCall(i int, result1 v1alpha2.ResolvedClusterStack, result2 error) {
	_ = "STUB: not implemented"
	return
}

func (fake *FakeClusterStackReader) Invocations() map[string][][]interface{} {
	_ = "STUB: not implemented"
	return nil
}

func (fake *FakeClusterStackReader) recordInvocation(key string, args []interface{}) {
	_ = "STUB: not implemented"
	return
}

var _ clusterstack.ClusterStackReader = new(FakeClusterStackReader)
