//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
 * Copyright 2019 The original author or authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Blob) DeepCopyInto(out *Blob) {
	_ = "STUB: not implemented"

	// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Blob.
	return
}

func (in *Blob) DeepCopy() *Blob { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BuildBuilderSpec) DeepCopyInto(out *BuildBuilderSpec) { _ = "STUB: not implemented"; return }

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BuildBuilderSpec.
func (in *BuildBuilderSpec) DeepCopy() *BuildBuilderSpec { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BuildStack) DeepCopyInto(out *BuildStack) {
	_ = "STUB: not implemented"

	// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BuildStack.
	return
}

func (in *BuildStack) DeepCopy() *BuildStack { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BuildpackInfo) DeepCopyInto(out *BuildpackInfo) {
	_ = "STUB: not implemented"

	// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BuildpackInfo.
	return
}

func (in *BuildpackInfo) DeepCopy() *BuildpackInfo { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BuildpackMetadata) DeepCopyInto(out *BuildpackMetadata) {
	_ = "STUB: not implemented"
	return

	// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BuildpackMetadata.
}

func (in *BuildpackMetadata) DeepCopy() *BuildpackMetadata { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BuildpackRef) DeepCopyInto(out *BuildpackRef) { _ = "STUB: not implemented"; return }

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BuildpackRef.
func (in *BuildpackRef) DeepCopy() *BuildpackRef { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BuildpackStack) DeepCopyInto(out *BuildpackStack) { _ = "STUB: not implemented"; return }

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BuildpackStack.
func (in *BuildpackStack) DeepCopy() *BuildpackStack { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BuildpackStatus) DeepCopyInto(out *BuildpackStatus) { _ = "STUB: not implemented"; return }

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BuildpackStatus.
func (in *BuildpackStatus) DeepCopy() *BuildpackStatus { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BuildpackageInfo) DeepCopyInto(out *BuildpackageInfo) {
	_ = "STUB: not implemented"

	// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BuildpackageInfo.
	return
}

func (in *BuildpackageInfo) DeepCopy() *BuildpackageInfo { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CNBBinding) DeepCopyInto(out *CNBBinding) { _ = "STUB: not implemented"; return }

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CNBBinding.
func (in *CNBBinding) DeepCopy() *CNBBinding { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in CNBBindings) DeepCopyInto(out *CNBBindings) { _ = "STUB: not implemented"; return }

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CNBBindings.
func (in CNBBindings) DeepCopy() CNBBindings { _ = "STUB: not implemented"; return *new(CNBBindings) }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Condition) DeepCopyInto(out *Condition) { _ = "STUB: not implemented"; return }

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Condition.
func (in *Condition) DeepCopy() *Condition { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Git) DeepCopyInto(out *Git) {
	_ = "STUB: not implemented"

	// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Git.
	return
}

func (in *Git) DeepCopy() *Git { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageSource) DeepCopyInto(out *ImageSource) {
	_ = "STUB: not implemented"

	// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageSource.
	return
}

func (in *ImageSource) DeepCopy() *ImageSource { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotaryConfig) DeepCopyInto(out *NotaryConfig) { _ = "STUB: not implemented"; return }

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotaryConfig.
func (in *NotaryConfig) DeepCopy() *NotaryConfig { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotarySecretRef) DeepCopyInto(out *NotarySecretRef) {
	_ = "STUB: not implemented"

	// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotarySecretRef.
	return
}

func (in *NotarySecretRef) DeepCopy() *NotarySecretRef { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotaryV1Config) DeepCopyInto(out *NotaryV1Config) { _ = "STUB: not implemented"; return }

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotaryV1Config.
func (in *NotaryV1Config) DeepCopy() *NotaryV1Config { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrderEntry) DeepCopyInto(out *OrderEntry) { _ = "STUB: not implemented"; return }

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrderEntry.
func (in *OrderEntry) DeepCopy() *OrderEntry { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Registry) DeepCopyInto(out *Registry) { _ = "STUB: not implemented"; return }

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Registry.
func (in *Registry) DeepCopy() *Registry { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResolvedBlobSource) DeepCopyInto(out *ResolvedBlobSource) {
	_ = "STUB: not implemented"
	return

	// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResolvedBlobSource.
}

func (in *ResolvedBlobSource) DeepCopy() *ResolvedBlobSource { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResolvedGitSource) DeepCopyInto(out *ResolvedGitSource) {
	_ = "STUB: not implemented"
	return

	// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResolvedGitSource.
}

func (in *ResolvedGitSource) DeepCopy() *ResolvedGitSource { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResolvedRegistrySource) DeepCopyInto(out *ResolvedRegistrySource) {
	_ = "STUB: not implemented"
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResolvedRegistrySource.
func (in *ResolvedRegistrySource) DeepCopy() *ResolvedRegistrySource {
	_ = "STUB: not implemented"
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResolvedSourceConfig) DeepCopyInto(out *ResolvedSourceConfig) {
	_ = "STUB: not implemented"
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResolvedSourceConfig.
func (in *ResolvedSourceConfig) DeepCopy() *ResolvedSourceConfig {
	_ = "STUB: not implemented"
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceConfig) DeepCopyInto(out *SourceConfig) { _ = "STUB: not implemented"; return }

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceConfig.
func (in *SourceConfig) DeepCopy() *SourceConfig { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Status) DeepCopyInto(out *Status) { _ = "STUB: not implemented"; return }

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Status.
func (in *Status) DeepCopy() *Status { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolatileTime) DeepCopyInto(out *VolatileTime) { _ = "STUB: not implemented"; return }

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolatileTime.
func (in *VolatileTime) DeepCopy() *VolatileTime { _ = "STUB: not implemented"; return nil }
