// Code generated by counterfeiter. DO NOT EDIT.
package buildpackfakes

import (
	"sync"

	"github.com/google/go-containerregistry/pkg/authn"
	"github.com/pivotal/kpack/pkg/apis/core/v1alpha1"
	"github.com/pivotal/kpack/pkg/reconciler/buildpack"
)

type FakeStoreReader struct {
	ReadStub        func(authn.Keychain, []v1alpha1.ImageSource) ([]v1alpha1.BuildpackStatus, error)
	readMutex       sync.RWMutex
	readArgsForCall []struct {
		arg1 authn.Keychain
		arg2 []v1alpha1.ImageSource
	}
	readReturns struct {
		result1 []v1alpha1.BuildpackStatus
		result2 error
	}
	readReturnsOnCall map[int]struct {
		result1 []v1alpha1.BuildpackStatus
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeStoreReader) Read(arg1 authn.Keychain, arg2 []v1alpha1.ImageSource) ([]v1alpha1.BuildpackStatus, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (fake *FakeStoreReader) ReadCallCount() int { _ = "STUB: not implemented"; return 0 }

func (fake *FakeStoreReader) ReadCalls(stub func(authn.Keychain, []v1alpha1.ImageSource) ([]v1alpha1.BuildpackStatus, error)) {
	_ = "STUB: not implemented"
	return
}

func (fake *FakeStoreReader) ReadArgsForCall(i int) (authn.Keychain, []v1alpha1.ImageSource) {
	_ = "STUB: not implemented"
	return *new(authn.Keychain), nil
}

func (fake *FakeStoreReader) ReadReturns(result1 []v1alpha1.BuildpackStatus, result2 error) {
	_ = "STUB: not implemented"
	return
}

func (fake *FakeStoreReader) ReadReturnsOnCall(i int, result1 []v1alpha1.BuildpackStatus, result2 error) {
	_ = "STUB: not implemented"
	return
}

func (fake *FakeStoreReader) Invocations() map[string][][]interface{} {
	_ = "STUB: not implemented"
	return nil
}

func (fake *FakeStoreReader) recordInvocation(key string, args []interface{}) {
	_ = "STUB: not implemented"
	return
}

var _ buildpack.StoreReader = new(FakeStoreReader)
