/*
 * Copyright 2019 The original author or authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by client-gen. DO NOT EDIT.

package versioned

import (
	http "net/http"

	kpackv1alpha1 "github.com/pivotal/kpack/pkg/client/clientset/versioned/typed/build/v1alpha1"
	kpackv1alpha2 "github.com/pivotal/kpack/pkg/client/clientset/versioned/typed/build/v1alpha2"
	discovery "k8s.io/client-go/discovery"
	rest "k8s.io/client-go/rest"
)

type Interface interface {
	Discovery() discovery.DiscoveryInterface
	KpackV1alpha1() kpackv1alpha1.KpackV1alpha1Interface
	KpackV1alpha2() kpackv1alpha2.KpackV1alpha2Interface
}

// Clientset contains the clients for groups.
type Clientset struct {
	*discovery.DiscoveryClient
	kpackV1alpha1 *kpackv1alpha1.KpackV1alpha1Client
	kpackV1alpha2 *kpackv1alpha2.KpackV1alpha2Client
}

// KpackV1alpha1 retrieves the KpackV1alpha1Client
func (c *Clientset) KpackV1alpha1() kpackv1alpha1.KpackV1alpha1Interface {
	_ = "STUB: not implemented"
	return *

	// KpackV1alpha2 retrieves the KpackV1alpha2Client
	new(kpackv1alpha1.KpackV1alpha1Interface)
}

func (c *Clientset) KpackV1alpha2() kpackv1alpha2.KpackV1alpha2Interface {
	_ = "STUB: not implemented"
	return *

	// Discovery retrieves the DiscoveryClient
	new(kpackv1alpha2.KpackV1alpha2Interface)
}

func (c *Clientset) Discovery() discovery.DiscoveryInterface {
	_ = "STUB: not implemented"
	return *new(discovery.DiscoveryInterface)
}

// NewForConfig creates a new Clientset for the given config.
// If config's RateLimiter is not set and QPS and Burst are acceptable,
// NewForConfig will generate a rate-limiter in configShallowCopy.
// NewForConfig is equivalent to NewForConfigAndClient(c, httpClient),
// where httpClient was generated with rest.HTTPClientFor(c).
func NewForConfig(c *rest.Config) (*Clientset, error) { _ = "STUB: not implemented"; return nil, nil }

// share the transport between all clients

// NewForConfigAndClient creates a new Clientset for the given config and http client.
// Note the http client provided takes precedence over the configured transport values.
// If config's RateLimiter is not set and QPS and Burst are acceptable,
// NewForConfigAndClient will generate a rate-limiter in configShallowCopy.
func NewForConfigAndClient(c *rest.Config, httpClient *http.Client) (*Clientset, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewForConfigOrDie creates a new Clientset for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *Clientset { _ = "STUB: not implemented"; return nil }

// New creates a new Clientset for the given RESTClient.
func New(c rest.Interface) *Clientset { _ = "STUB: not implemented"; return nil }
