// Code generated by counterfeiter. DO NOT EDIT.
package sourceresolverfakes

import (
	"context"
	"sync"

	"github.com/pivotal/kpack/pkg/apis/build/v1alpha2"
	"github.com/pivotal/kpack/pkg/apis/core/v1alpha1"
	"github.com/pivotal/kpack/pkg/reconciler/sourceresolver"
)

type FakeResolver struct {
	CanResolveStub        func(*v1alpha2.SourceResolver) bool
	canResolveMutex       sync.RWMutex
	canResolveArgsForCall []struct {
		arg1 *v1alpha2.SourceResolver
	}
	canResolveReturns struct {
		result1 bool
	}
	canResolveReturnsOnCall map[int]struct {
		result1 bool
	}
	ResolveStub        func(context.Context, *v1alpha2.SourceResolver) (v1alpha1.ResolvedSourceConfig, error)
	resolveMutex       sync.RWMutex
	resolveArgsForCall []struct {
		arg1 context.Context
		arg2 *v1alpha2.SourceResolver
	}
	resolveReturns struct {
		result1 v1alpha1.ResolvedSourceConfig
		result2 error
	}
	resolveReturnsOnCall map[int]struct {
		result1 v1alpha1.ResolvedSourceConfig
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeResolver) CanResolve(arg1 *v1alpha2.SourceResolver) bool {
	_ = "STUB: not implemented"
	return false
}

func (fake *FakeResolver) CanResolveCallCount() int { _ = "STUB: not implemented"; return 0 }

func (fake *FakeResolver) CanResolveCalls(stub func(*v1alpha2.SourceResolver) bool) {
	_ = "STUB: not implemented"
	return
}

func (fake *FakeResolver) CanResolveArgsForCall(i int) *v1alpha2.SourceResolver {
	_ = "STUB: not implemented"
	return nil
}

func (fake *FakeResolver) CanResolveReturns(result1 bool) { _ = "STUB: not implemented"; return }

func (fake *FakeResolver) CanResolveReturnsOnCall(i int, result1 bool) {
	_ = "STUB: not implemented"
	return
}

func (fake *FakeResolver) Resolve(arg1 context.Context, arg2 *v1alpha2.SourceResolver) (v1alpha1.ResolvedSourceConfig, error) {
	_ = "STUB: not implemented"
	return *new(v1alpha1.ResolvedSourceConfig), nil
}

func (fake *FakeResolver) ResolveCallCount() int { _ = "STUB: not implemented"; return 0 }

func (fake *FakeResolver) ResolveCalls(stub func(context.Context, *v1alpha2.SourceResolver) (v1alpha1.ResolvedSourceConfig, error)) {
	_ = "STUB: not implemented"
	return
}

func (fake *FakeResolver) ResolveArgsForCall(i int) (context.Context, *v1alpha2.SourceResolver) {
	_ = "STUB: not implemented"
	return *new(context.Context), nil
}

func (fake *FakeResolver) ResolveReturns(result1 v1alpha1.ResolvedSourceConfig, result2 error) {
	_ = "STUB: not implemented"
	return
}

func (fake *FakeResolver) ResolveReturnsOnCall(i int, result1 v1alpha1.ResolvedSourceConfig, result2 error) {
	_ = "STUB: not implemented"
	return
}

func (fake *FakeResolver) Invocations() map[string][][]interface{} {
	_ = "STUB: not implemented"
	return nil
}

func (fake *FakeResolver) recordInvocation(key string, args []interface{}) {
	_ = "STUB: not implemented"
	return
}

var _ sourceresolver.Resolver = new(FakeResolver)
