// Code generated by counterfeiter. DO NOT EDIT.
package sourceresolverfakes

import (
	"sync"

	"github.com/pivotal/kpack/pkg/apis/build/v1alpha2"
	"github.com/pivotal/kpack/pkg/reconciler/sourceresolver"
)

type FakeEnqueuer struct {
	EnqueueStub        func(*v1alpha2.SourceResolver) error
	enqueueMutex       sync.RWMutex
	enqueueArgsForCall []struct {
		arg1 *v1alpha2.SourceResolver
	}
	enqueueReturns struct {
		result1 error
	}
	enqueueReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeEnqueuer) Enqueue(arg1 *v1alpha2.SourceResolver) error {
	_ = "STUB: not implemented"
	return nil
}

func (fake *FakeEnqueuer) EnqueueCallCount() int { _ = "STUB: not implemented"; return 0 }

func (fake *FakeEnqueuer) EnqueueCalls(stub func(*v1alpha2.SourceResolver) error) {
	_ = "STUB: not implemented"
	return
}

func (fake *FakeEnqueuer) EnqueueArgsForCall(i int) *v1alpha2.SourceResolver {
	_ = "STUB: not implemented"
	return nil
}

func (fake *FakeEnqueuer) EnqueueReturns(result1 error) { _ = "STUB: not implemented"; return }

func (fake *FakeEnqueuer) EnqueueReturnsOnCall(i int, result1 error) {
	_ = "STUB: not implemented"
	return
}

func (fake *FakeEnqueuer) Invocations() map[string][][]interface{} {
	_ = "STUB: not implemented"
	return nil
}

func (fake *FakeEnqueuer) recordInvocation(key string, args []interface{}) {
	_ = "STUB: not implemented"
	return
}

var _ sourceresolver.Enqueuer = new(FakeEnqueuer)
